name: xview3
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia

dependencies:
  - cudatoolkit=11.1
  - python>=3.8
  - pytorch
  - pytorch-gpu
  - numpy
  
  - _libgcc_mutex
  - _openmp_mutex
  - affine
  - attrs
  - bokeh
  - boost-cpp
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - cfitsio
  - cftime
  - chardet
  - click
  - click-plugins
  - cligj
  - cloudpickle
  - cryptography
  - curl
  - cycler
  - cython
  - cytoolz
  - dask
  - dask-core
  - distributed
  - expat
  - fiona
  - fontconfig
  - freetype
  - freexl
  - fsspec
  - gdal
  - geopandas
  - geos
  - geotiff
  - gettext
  - giflib
  - haversine
  - hdf4
  - hdf5
  - heapdict
  - icu
  - idna
  - jinja2
  - joblib
  - jpeg
  - json-c
  - kealib
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - libblas
  - libcblas
  - libcurl
  - libdap4
  - libedit
  - libev
  - libffi
  - libgcc
  - libgcc-ng
  - libgdal
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libgomp
  - libiconv
  - libkml
  - liblapack
  - libnetcdf
  - libnghttp2
  - libopenblas
  - libpng
  - libpq
  - librttopo
  - libspatialindex
  - libspatialite
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libxml2
  - locket
  - lz4-c
  - markupsafe
  - matplotlib-base
  - msgpack-python
  - munch
  - ncurses
  - netcdf4
  - olefile
  - openjpeg
  - openssl
  - packaging
  - pandas
  - partd
  - pcre
  - pillow
  - pip
  - pixman
  - poppler
  - poppler-data
  - postgresql
  - proj
  - psutil
  - pthread-stubs
  - pycocotools
  - pycparser
  - pyopenssl
  - pyparsing
  - pyproj
  - pysocks
  - python-dateutil
  - python_abi
  - pytz
  - pyyaml
  - rasterio
  - readline
  - requests
  - rtree
  - scikit-learn
  - scipy
  - setuptools
  - shapely
  - six
  - snuggs
  - sortedcontainers
  - sqlite
  - tblib
  - threadpoolctl
  - tiledb
  - tk
  - toolz
  - tornado
  - typing_extensions
  - tzcode
  - tzdata
  - urllib3
  - wheel
  - xerces-c
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - zict
  - zlib
  - zstd
  - pip:
    - aiohttp
    - aiohttp-cors
    - aioredis
    - async-timeout
    - blessings
    - cachetools
    - colorama
    - colorful
    - filelock
    - geojson
    - geomet
    - google-api-core
    - google-auth
    - googleapis-common-protos
    - gpustat
    - grpcio
    - hiredis
    - html2text
    - jsonschema
    - multidict
    - nvidia-ml-py3
    - opencensus
    - opencensus-context
    - prometheus-client
    - protobuf
    - py-spy
    - pyasn1
    - pyasn1-modules
    - pydantic
    - pyrsistent
    - ray
    - redis
    - rsa
    - sentinelsat
    - torchvision
    - tqdm
    - yarl
